### ISSUE TITLE
Home Page - Fix UP 

### ISSUE THREAD

**Issue by smartopian** [MassachusettsLegalHackers/orgsetup#10]
Tasks
[] - Add a RSS feed from blog.consentreceipt.
[] -Make RSS as feature (first Item in page)
[] - Add Developer resources
[] - add a button on home page to a form

**Comment by dazzaji** [comment]
item (1) here is some code for the RSS feed from the blog.  i will look into implementing it at the github site.  

item (2) creating rss feeds from github sites (or any flat site that does not use traditional server hosted code such as php) is not an expected or common function and should be considered out of scope.  for updates related to the developer site, developers should (1) star/join/watch/sync with and otherwise participate in or contribute to the repository where the development is happening and (2) signup to an email list and get a notice when a major new release is coming or there is some other important developer news or alerts they want to receive.  Please  keep in mind that this site is related solely to the developer stuff happening in github and it is not the general purpose blog.  

Here is an example of the sort of activity feed a developer can get using normal GitHub functionality and could be linked from the site: https://github.com/OpenConsent/ConsentReceipt/commits/master.atom

item (3) Caitlin has a stub for developer resources but there is not a lot in place.  In theory, some general links to Node.js and other relevant code bases and tutorials could be identified and listed but that may not be of sufficient value to warrant a section of the site titled "Developer Resources".  I'm not really sure what you have in mind for that, but if you can provide a listing with links and descriptions for all the developer resources you want to have on a developer resources section of the site so Caitlin can put it together.  In a sense, the developer resources are the entire site and repository it lives in. 

item (4) a button to a form?  that sounds pretty weird.  we could try displaying the current link from the home page to the example externalized consent receipt form (which is all we have to work with at the moment) in the form of a material design style button.  Something like this perhaps? 
![components_buttons_main20](https://cloud.githubusercontent.com/assets/2357755/11710068/a39913da-9eea-11e5-8a8c-e613e340a6a1.png)

**Comment by dazzaji** [comment]
Done!

![screen shot 2015-12-11 at 7 08 08 am](https://cloud.githubusercontent.com/assets/2357755/11743528/3fedfbce-9fd6-11e5-89e3-240a5313fb5a.png)
